version: '3.4'
services:

  web:
    image: abilson/ptb-web:nginx-alpine
    build:
      context: ./web
      target: prod
    ports:
      - "4200:80"

  server:
    image: abilson/ptb-server:2.1
    build:
      context: ./service
      target: prod
    ports:
      - "5000:5000"

  json-server:
    image: abilson/ptb-json-server:12.11.1-alpine
    build:
      context: ./web/json-server
      target: prod
    ports:
      - "5000:5000"
