version: '3.4'
services:

  web:
    image: ptb-web-dev:12.11.1-alpine
    build:
      target: dev
    ports:
      - "49153:49153"
    volumes: 
      - ./web:/srv
    command: ["npm", "run", "start"]

  server:
    image: ptb-server-dev:2.1
    build:
      target: dev
    volumes: 
      - ./service:/srv
    command: ["dotnet", "watch", "run"]

  json-server:
    image: ptb-json-server-dev:12.11.1-alpine
    build:
      target: dev
    volumes: 
      - ./web/json-server:/srv
    command: ["json-server", "db.json"]

