version: '3.3'
services:
  web:
    image: ptb-web-dev:latest
    build: 
      dockerfile: Dockerfile-dev
    volumes:
      - ./web:/src
  server:
    image: ptb-server-dev:latest
    build: 
      dockerfile: Dockerfile-dev
    volumes:
      - ./service:/src
