version: '3.3'
services:
  web:
    image: ptb-web:latest
    build: 
      context: ./web
    ports: 
      - "4200:80"
  server:
    image: ptb-server:latest
    build: 
      context: ./service
    ports:
      - "5000:80"
    volumes: 
      - ./logs:/app/logs
