version: '3.4'
services:

  web:
    image: abilson/ptb-web
    build:
      context: ./web
      target: prod
    ports:
      - "4200:80"

  server:
    image: abilson/ptb-server
    build:
      context: ./service
      target: prod
    ports:
      - "5000:80"

  json-server:
    image: abilson/ptb-json-server
    build:
      context: ./web/json-server
      target: prod
    ports:
      - "5000:80"
