version: '3.3'
services:
  server:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    working_dir: /src/PTB.Web
    ports:
      - "5000:5000"
    volumes: 
      - ./:/src
    command: ["dotnet", "watch", "run"]
