version: '3.3'
services:
  web:
    image: node:12.11.1
    working_dir: /src
    ports:
      - "4200:3000"
    volumes: 
      - ./:/src
    command: ["npm", "run", "start"]
  server:
    image: clue/json-server
    ports:
      - "5000:80"
    volumes: 
      - ./json-server/db.json:/data/db.json
