version: '3.3'
services:
  web:
    image: node:12.11.1
    working_dir: /src
    ports:
      - "4200:80"
      - "49153:49153"
    volumes: 
      - ./:/src
    depends_on:
      - server
    command: ["npm", "run", "start"]
  server:
    image: abilson/ptb-json-server
    build:
      context: ./json-server
      dockerfile: ./Dockerfile-dev
    ports:
      - "5000:80"
    volumes: 
      - ./json-server:/data
